site_name: GuanSheng的个人网站
site_url: https://guansheng.github.io/mymkdocs/
site_author: GuanSheng
theme:
  name: material
  features:
    - navigation.expand
plugins:
  - search

markdown_extensions:
  - toc:
      slugify: !!python/name:pymdownx.slugs.uslugify

extra:
  analytics:
    provider: google
    property: G-7PTMCYKC09